# Generated by Django 4.1.5 on 2023-01-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('available', models.IntegerField()),
                ('img', models.FileField(upload_to='media/event')),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=60)),
                ('cost', models.FloatField()),
                ('status', models.CharField(default='paid', max_length=100)),
                ('status2', models.CharField(default='paid', max_length=100)),
            ],
        ),
    ]
