# Generated by Django 4.1.5 on 2023-01-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='status2',
        ),
    ]
