# Generated by Django 4.1.5 on 2023-01-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0003_paymentmodel_test1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='test1',
        ),
    ]
