# Generated by Django 4.1.5 on 2023-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0004_remove_paymentmodel_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='no_of_seat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
