# Generated by Django 4.1.5 on 2023-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0006_alter_paymentmodel_no_of_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='no_of_seat',
            field=models.IntegerField(),
        ),
    ]
