# Generated by Django 4.1.5 on 2023-01-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0007_alter_paymentmodel_no_of_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
