# Generated by Django 4.1.5 on 2023-01-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0009_alter_events_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
    ]
