# Generated by Django 4.1.5 on 2023-01-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0010_remove_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='available',
            field=models.IntegerField(default='01/01/2000'),
        ),
    ]
