# Generated by Django 4.1.5 on 2023-01-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0011_alter_events_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='times',
            field=models.CharField(default='01/01/2000', max_length=100),
        ),
    ]
