# Generated by Django 4.1.5 on 2023-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0012_events_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='Enter The Location', max_length=200),
        ),
    ]
