# Generated by Django 4.1.5 on 2023-01-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0013_events_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='cvvs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='expiry_dates',
            field=models.CharField(default='No data', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='name_on_cards',
            field=models.CharField(default='No data', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='number_of_cards',
            field=models.IntegerField(default=0),
        ),
    ]
