# Generated by Django 4.1.5 on 2023-01-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic_day_2023', '0016_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='cvvs',
            field=models.CharField(max_length=100),
        ),
    ]
